version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "WebSocketApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jthb8z4ocxwj"
s3_prefix = "WebSocketApp"
region = "us-east-1"

confirm_changeset = true
capabilities = "CAPABILITY_IAM"

